### ISSUE TITLE
执行的时候会提示 类型报错

### ISSUE THREAD

**Issue by LuckyDogJJ** [abanger/sitelink#1]
'NoneType' object has no attribute 'split'
环境：
python  3.9
certifi    2020.12.5
chardet    4.0.0
idna       2.10
numpy      1.19.4
pip        20.3.3
requests   2.25.1
selenium   3.141.0
setuptools 49.2.1
urllib3    1.26.2
![image](https://user-images.githubusercontent.com/13271610/102842896-04441380-4443-11eb-9b01-fa6f75a3fa59.png)

**Comment by abanger** [comment]
URL是什么？
main.py :
    domain = get_domain(URL)
    print(domain)
用print(domain)，查查域名是不是正常？

**Comment by LuckyDogJJ** [comment]
> URL是什么？
> main.py :
> domain = get_domain(URL)
> print(domain)
> 用print(domain)，查查域名是不是正常？

配置的URL 是: http://www.sipac.gov.cn/

**Comment by LuckyDogJJ** [comment]
> > URL是什么？
> > main.py :
> > domain = get_domain(URL)
> > print(domain)
> > 用print(domain)，查查域名是不是正常？
> 
> 配置的URL 是: http://www.sipac.gov.cn/

返回的域名是None

**Comment by abanger** [comment]
下载后直接配置如下，其他不变，本地测试正常，自己添加各函数打印print(domain)查那里出错。现有信息无法判断出错地方。
 #检查主站
URL = "http://www.sipac.gov.cn"

![image](https://user-images.githubusercontent.com/5539/103086961-02d04200-4621-11eb-8d99-b6f9622de195.png)

**Comment by LuckyDogJJ** [comment]
是否有详细的配置教程，或者操作手册

**Comment by abanger** [comment]
> 是否有详细的配置教程，或者操作手册

还没有，URL改一下，其他可以不要更改了。

**Comment by LuckyDogJJ** [comment]
domain  返回的一直是None ，是不是我环境配置有问题了。



oyj7@hotmail.com
 
发件人： 阿笨哥
发送时间： 2020-12-25 09:17
收件人： abanger/sitelink
抄送： LuckyDogJJ; Author
主题： Re: [abanger/sitelink] 执行的时候会提示 类型报错 (#1)
是否有详细的配置教程，或者操作手册
还没有，URL改一下，其他可以不要更改了。

**Comment by abanger** [comment]
> domain 返回的一直是None ，是不是我环境配置有问题了。 oyj7@hotmail.com 发件人： 阿笨哥 发送时间： 2020-12-25 09:17 收件人： abanger/sitelink 抄送： LuckyDogJJ; Author 主题： Re: [abanger/sitelink] 执行的时候会提示 类型报错 (#1) 是否有详细的配置教程，或者操作手册 还没有，URL改一下，其他可以不要更改了。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

开发环境参考下：
- selenium=3.141.0=py36he774522_0
- urllib3=1.24.2=py36_0  
- numpy==1.18.5
- requests==2.23.0
- selenium=3.141.0=py36he774522_0
Google Chrome  87.0.4280.66
chromedriver 87.0.4280
